name: wyrd_web
description: "Join the Wyrd-wide Web to build more Empathetech communities. Ones free from the controlling hand of tech giants."
version: 1.0.0+2
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Flutter (Google)
  go_router: ^14.8.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4

  # Community
  flutter_localized_locales: ^2.0.5

  # Empathetech
  efui_bios:
    path: ../efui_bios/
  empathetech_flutter_ui:
    path: ../empathetech_flutter_ui/

dev_dependencies:
  dependency_validator: ^5.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/web-of-wyrd.png

flutter_launcher_icons:
  image_path: assets/images/web-of-wyrd.png
  adaptive_icon_foreground: assets/images/web-of-wyrd.png
  adaptive_icon_background: "#F5F5F5"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  image: assets/images/web-of-wyrd.png
  color: "#F5F5F5"
  android: true
  ios: true
  web: true