# wyrd_web
# Copyright (c) 2025 Empathetech LLC. All rights reserved.
# See LICENSE for distribution and usage details.

apiVersion: v1

kind: ConfigMap
metadata:
  name: config-dev
  
data:
  DB_HOST: db
  DB_PORT: "5432"
  GOTRACEBACK: all