apiVersion: v1
kind: Pod

metadata:
  name: api
  labels:
    name: api

spec:
  containers:
  - name: api
    image: smoke-signal/api
    imagePullPolicy: Never
    resources:
      limits:
        memory: "2Gi"
        cpu: "500m"
    env:
      - name: SESSION_STORE_KEY
        valueFrom:
          secretKeyRef:
            name: session-key
            key: session-key
      - name: CORS_ALLOW_ORIGIN
        value: "[\"http://localhost:3000\"]"
    envFrom:
      - configMapRef:
          name: config-dev
    ports:
      - containerPort: 8080
